---
# tasks file for ansible-role-icinga2

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ icinga2_log_dir }}"
    mode: 0755
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    state: directory
  notify: Restart icinga2

- name: Create db directory
  file:
    path: "{{ icinga2_db_dir }}"
    mode: 0755
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    state: directory
  notify: Restart icinga2

- name: Create icinga2.conf
  template:
    src: icinga2.conf.j2
    dest: "{{ icinga2_conf_file }}"
    validate: echo %s
  notify: Restart icinga2

- name: Start icinga2
  service:
    name: "{{ icinga2_service }}"
    enabled: true
    state: started
